.eqv    OPEN_PAR        0
.eqv    CLOSE_PAR       1
.eqv    OPEN_BRAC       2
.eqv    CLOSE_BRAC      3
.eqv    SEMICOLON       4
.eqv    ASSIGN          5
.eqv    BIT_COMPL       6
.eqv    PLUS            7
.eqv    MINUS           8
.eqv    NEGATION        9
.eqv    KEYWORD_INT     10
.eqv    KEYWORD_RETURN  11
.eqv    LITERAL_INT     12
.eqv    LITERAL_HEX     13
.eqv    IDENT           14
.eqv    TOKEN_END       15
.eqv    TMULT           16
.eqv    TDIV            17
.eqv    TAND            18
.eqv    TOR             19
.eqv    EQUAL           20
.eqv    NOT_EQUAL       21
.eqv    LESS_THAN       22
.eqv    LESS_EQUAL      23
.eqv    GREATER_THAN    24
.eqv    GREATER_EQUAL   25
.eqv    BIT_AND         26
.eqv    BIT_OR          27
